title: ""
labels: ["BUG"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Descrição do Bug
      description: Por favor, forneça uma descrição detalhada do bug. Descreva o problema em detalhes, incluindo mensagens de erro, comportamento inesperado, etc.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Passos para Reproduzir
      description: Forneça os passos para reproduzir o bug.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: input
    id: expected-behavior
    attributes:
      label: Comportamento Esperado
      description: O que você esperava que acontecesse?
    validations:
      required: false
  - type: input
    id: actual-behavior
    attributes:
      label: Comportamento Real
      description: O que realmente aconteceu?
    validations:
      required: false
 
  - type: dropdown
    id: bug-area
    attributes:
      label: Onde no projeto você encontrou o bug?
      multiple: true
      options:
        - Painel
        - Loja
        - PDV
        - Desktop
        - App de Impressão
        - Outro
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Obrigado por relatar o bug!
        Nós investigaremos e trabalharemos para corrigir o problema o mais rápido possível.

