## Descrição do problema

- [ ] Eu descrevi o problema com clareza.

## Como reproduzir
1. Passo 1
2. Passo 2
3. Passo 3
4. Ver o erro

## Comportamento esperado
Explique o que deveria acontecer

## Captura de tela
Se possível, adicione capturas de tela ou logs para ajudar a ilustrar o problema.
