title: "[Relatório de Bug] "
labels: ["Bug", "Relatório"]
body:
  - type: markdown
    attributes:
      value: |
        Por favor, preencha os detalhes abaixo para relatar um bug.
  - type: input
    id: bug-title
    attributes:
      label: Título do Bug
      description: Um título breve e descritivo para o bug.
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Descrição do Bug
      description: Por favor, forneça uma descrição detalhada do bug.
      value: |
        Descreva o problema em detalhes, incluindo mensagens de erro, comportamento inesperado, etc.
      render: markdown
    validations:
      required: true
